name: expense_tracker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_ui:
    path: packages/app_ui
  auto_route: ^7.7.1
  bloc: ^8.1.2
  cloud_firestore: ^4.8.4
  collection: ^1.17.1
  dartz: ^0.10.1
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  get_it: ^7.6.0
  google_sign_in: ^6.1.4
  hydrated_bloc: ^9.1.2
  injectable: ^2.1.2
  injectable_generator: ^2.1.6
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.0.15
  rxdart: ^0.27.7

dev_dependencies:
  auto_route_generator: ^7.2.0
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  firebase_auth_mocks: ^0.12.0
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  google_sign_in_mocks: ^0.3.0
  mockingjay: ^0.3.0
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  intl: ^0.18.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_gen:
  output: lib/gen/
  line_length: 80
