name: expense_tracker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.2
  cloud_firestore: ^4.8.4
  collection: ^1.18.0
  dartz: ^0.10.1
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  form_inputs:
    path: packages/form_inputs
  formz: ^0.6.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0

  # 
  go_router: 
    git:
      url: https://github.com/chunhtai/packages.git
      ref: 6fc5699
      path: packages/go_router
      
  google_sign_in: ^6.1.4
  hydrated_bloc: ^9.1.2
  injectable: ^2.1.2
  injectable_generator: ^2.1.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  firebase_auth_mocks: ^0.12.0
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.2.4
  google_sign_in_mocks: ^0.3.0
  json_serializable: ^6.7.1
  mockingjay: ^0.3.0
  mockito: ^5.4.2
  very_good_analysis: ^5.0.0+1

dependency_overrides:
  intl: ^0.18.1
  collection: ^1.18.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_gen:
  output: lib/gen/
  line_length: 80
